# Generated by Django 2.1.7 on 2019-04-11 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('year', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=256)),
                ('units', models.PositiveIntegerField()),
                ('offeredSem1', models.BooleanField()),
                ('offeredSem2', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CoursesInSubplanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CourseModel')),
            ],
        ),
        migrations.CreateModel(
            name='DegreeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('year', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=256)),
                ('units', models.PositiveIntegerField()),
                ('degreeType', models.CharField(choices=[('ugrad-sing', 'Undergraduate Single Pass Degree'), ('ugrad-doub', 'Undergraduate Flexible Double Degree'), ('hon', 'Honours Degree'), ('mast-sing', 'Masters Single Degree'), ('mast-adv', 'Masters (Advanced) Degree'), ('mast-doub', 'Masters Flexible Double Degree'), ('vert_doub', 'Vertical Flexible Double Degree')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubplanModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('year', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=256)),
                ('units', models.PositiveIntegerField()),
                ('planType', models.CharField(choices=[('MAJ', 'Major'), ('MIN', 'Minor'), ('SPEC', 'Specialisation')], max_length=4)),
                ('courses', models.ManyToManyField(through='api.CoursesInSubplanModel', to='api.CourseModel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='degreemodel',
            unique_together={('code', 'year')},
        ),
        migrations.AddField(
            model_name='coursesinsubplanmodel',
            name='subplanId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SubplanModel'),
        ),
        migrations.AlterUniqueTogether(
            name='coursemodel',
            unique_together={('code', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='subplanmodel',
            unique_together={('code', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='coursesinsubplanmodel',
            unique_together={('subplanId', 'courseId')},
        ),
    ]
