# Generated by Django 2.1.7 on 2019-04-17 09:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreemodel',
            name='rules',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='degreemodel',
            name='degreeType',
            field=models.CharField(choices=[('ugrad-sing', 'Undergraduate Single Pass Degree'), ('ugrad-doub', 'Undergraduate Flexible Double Degree'), ('hon', 'Honours Degree'), ('mast-sing', 'Masters Single Degree'), ('mast-adv', 'Masters (Advanced) Degree'), ('mast-doub', 'Masters Flexible Double Degree'), ('vert_doub', 'Vertical Flexible Double Degree'), ('other', 'Other Degree')], max_length=10),
        ),
    ]
