# Generated by Django 2.1.7 on 2019-04-22 05:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190417_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreemodel',
            name='globalRequirements',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='degreemodel',
            name='degreeType',
            field=models.CharField(choices=[('ugrad-sing', 'Undergraduate Single Pass Degree'), ('ugrad-doub', 'Undergraduate Flexible Double Degree'), ('hon', 'Honours Degree'), ('mast-sing', 'Masters Single Degree'), ('mast-adv', 'Masters (Advanced) Degree'), ('mast-doub', 'Masters Flexible Double Degree'), ('vert-doub', 'Vertical Flexible Double Degree'), ('other', 'Other Degree')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='subplanmodel',
            unique_together={('year', 'name', 'planType'), ('code', 'year')},
        ),
    ]
