# Generated by Django 2.1.7 on 2019-05-01 03:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190422_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('year', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=256)),
                ('units', models.PositiveIntegerField()),
                ('programType', models.CharField(choices=[('ugrad-sing', 'Undergraduate Single Pass Degree'), ('ugrad-doub', 'Undergraduate Flexible Double Degree'), ('hon', 'Honours Degree'), ('mast-sing', 'Masters Single Degree'), ('mast-adv', 'Masters (Advanced) Degree'), ('mast-doub', 'Masters Flexible Double Degree'), ('vert-doub', 'Vertical Flexible Double Degree'), ('other', 'Other Degree')], max_length=10)),
                ('globalRequirements', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('rules', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='coursesinsubplanmodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coursesinsubplanmodel',
            name='courseId',
        ),
        migrations.RemoveField(
            model_name='coursesinsubplanmodel',
            name='subplanId',
        ),
        migrations.DeleteModel(
            name='DegreeModel',
        ),
        migrations.RemoveField(
            model_name='subplanmodel',
            name='courses',
        ),
        migrations.AddField(
            model_name='subplanmodel',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subplanmodel',
            name='rules',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='CoursesInSubplanModel',
        ),
        migrations.AlterUniqueTogether(
            name='programmodel',
            unique_together={('code', 'year'), ('name', 'year')},
        ),
    ]
