# Generated by Django 2.1.7 on 2019-05-16 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190508_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='test',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
