# Generated by Django 2.1.7 on 2019-05-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_coursemodel_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodel',
            old_name='test',
            new_name='lastUpdated',
        ),
    ]
