# Generated by Django 2.1.7 on 2019-05-16 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190517_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplanmodel',
            name='lastUpdated',
            field=models.DateField(default=datetime.datetime(2019, 3, 10, 0, 0)),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='lastUpdated',
            field=models.DateField(default=datetime.datetime(2019, 3, 10, 0, 0)),
        ),
    ]
