# Generated by Django 2.1.7 on 2019-05-16 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190517_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmodel',
            name='lastUpdated',
            field=models.DateField(default=datetime.datetime(2019, 3, 10, 0, 0)),
        ),
    ]
