# Generated by Django 2.1.7 on 2019-05-21 10:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_programmodel_lastupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='rules',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='lastUpdated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='programmodel',
            name='lastUpdated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subplanmodel',
            name='lastUpdated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
